//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewerly.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderComposition
    {
        public int OrderCompositionID { get; set; }
        public string Article { get; set; }
        public int Count { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
