//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewerly.Database
{
    using System;
    using System.Collections.Generic;

    public partial class Product
    {
        private string productPhoto;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderComposition = new HashSet<OrderComposition>();
        }

        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductUnit { get; set; }
        public decimal ProductCost { get; set; }
        public Nullable<int> ProductMaxDiscountAmount { get; set; }
        public string ProductManufacturer { get; set; }
        public string ProductSuppliers { get; set; }
        public string ProductCategory { get; set; }
        public Nullable<int> ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductDescription { get; set; }
        public string ProductPhoto { get {
                if (productPhoto=="")
                {
                    return "/image/picture.png";
                } 
                return productPhoto;
            } set => productPhoto = value; }

        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderComposition> OrderComposition { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
